version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-gadgets_store}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      - MYSQL_HOST=db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
