[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Note: You still need to add environment variables (secrets) in the Railway UI
# (Project -> Variables) for MYSQL_*, HUGGINGFACE_API_TOKEN, SECRET_KEY, etc.
